Repository CMU-313/nodebb-f24-team-five-guys, pull requests merged in 2024-10, with the labels that each got.

#34 US7: Created a User Guide and Added User Story 7 Section
  UserGuide.md
  dump.rdb
Labels: documentation

#38 Added in the UserGuide details and documentation for US10
  UserGuide.md
Labels: documentation

#37 US10: Add "Most Followers" tab to display all users ranked by their followers
  node_modules/nodebb-theme-harmony/templates/partials/users/item.tpl
  node_modules/nodebb-theme-harmony/templates/partials/users_list_menu.tpl
  node_modules/nodebb-theme-harmony/templates/users.tpl
  public/language/en-GB/users.json
  public/language/en-US/users.json
  public/openapi/components/schemas/UserObject.yaml
  public/openapi/read/users.yaml
  public/src/client/users.js
  src/controllers/users.js
  src/user/follow.js
  src/user/index.js
  test/api.js
  test/controllers.js
Labels: enhancement

#48 Integrated JSHint into the CI/CD Pipeline
  .github/workflows/test.yaml
  .jshintrc
  dump.rdb
  install/package.json
  src/api/users.js
  src/categories/watch.js
  src/cli/user.js
  src/controllers/accounts/chats.js
  src/controllers/helpers.js
  src/database/redis/connection.js
  src/flags.js
  src/groups/ownership.js
  src/messaging/rooms.js
  src/messaging/unread.js
  src/meta/configs.js
  src/meta/css.js
  src/notifications.js
  src/socket.io/categories.js
  src/socket.io/modules.js
  src/topics/follow.js
  src/topics/tags.js
  src/topics/unread.js
  src/user/admin.js
  src/user/auth.js
  src/user/categories.js
  src/user/email.js
  src/user/index.js
  src/user/online.js
  src/user/posts.js
Labels: enhancement, Analysis Tools
